# Generated by Django 2.2.1 on 2020-07-08 10:12

from django.db import migrations, models
import django.db.models.deletion
import employeesApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Indeterminate', 'Indeterminate')], max_length=16)),
                ('dob', models.DateField()),
                ('cnic_number', models.CharField(max_length=16)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('phone_1', models.CharField(blank=True, max_length=128)),
                ('phone_2', models.CharField(blank=True, max_length=128)),
                ('email_personal', models.EmailField(blank=True, max_length=192)),
                ('email_official', models.EmailField(blank=True, max_length=192)),
                ('designation', models.CharField(max_length=128)),
                ('joining_date', models.DateField()),
                ('city', models.ForeignKey(on_delete=models.SET(employeesApp.models.get_default_city), to='baseApp.City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Department')),
            ],
        ),
    ]
