# Generated by Django 2.2.1 on 2020-07-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeesApp', '0002_auto_20200708_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email_official',
            new_name='email_1',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email_personal',
            new_name='email_2',
        ),
    ]
