# Generated by Django 2.2.1 on 2020-07-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=16, unique=True)),
                ('province_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
