# Generated by Django 2.2.1 on 2020-07-08 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=192)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Company')),
            ],
        ),
    ]
