# Generated by Django 2.2.1 on 2020-07-03 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0002_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_code', models.CharField(max_length=8)),
                ('authority_name', models.CharField(max_length=128)),
                ('authority_address', models.CharField(max_length=256)),
                ('authority_phone', models.CharField(max_length=128)),
                ('authority_email', models.CharField(max_length=128)),
                ('authority_jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Province')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_code', models.CharField(max_length=8)),
                ('tax_description', models.CharField(max_length=64)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tax_authority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxesApp.TaxAuthority')),
            ],
        ),
    ]
