# Generated by Django 2.2.1 on 2020-07-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='tax_display_name',
            field=models.CharField(default='GST', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxauthority',
            name='authority_display_name',
            field=models.CharField(default='FBR', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='tax',
            name='tax_description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='authority_address',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='authority_code',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='authority_name',
            field=models.CharField(max_length=256),
        ),
    ]
