# Generated by Django 2.2.1 on 2020-06-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudbasic', '0005_auto_20200619_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=48, verbose_name='PO Number')),
                ('po_serial_number', models.IntegerField(blank=True, default=0)),
                ('po_date', models.DateField()),
                ('po_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Projects')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Suppliers')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.TaxRate')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_line_number', models.IntegerField(verbose_name='Line')),
                ('order_quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantity')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Purchase Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('variation_number', models.IntegerField(default=0)),
                ('variation_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Items', verbose_name='Item')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseApp.PurchaseOrder')),
            ],
        ),
    ]
