# Generated by Django 2.2.1 on 2020-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='read_status',
            field=models.IntegerField(default=0),
        ),
    ]
