# Generated by Django 2.2.1 on 2020-07-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseApp', '0003_auto_20200702_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemsApp.Item', verbose_name='Item'),
        ),
    ]
