# Generated by Django 2.2.1 on 2020-07-08 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseApp', '0005_auto_20200707_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsApp.Project'),
        ),
    ]
