# Generated by Django 2.2.1 on 2020-07-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0004_department'),
        ('saleordersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleOrderInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=56)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sale_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saleordersApp.SaleOrder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saleordersApp.SaleOrderItem')),
                ('sale_order_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saleorderinvoicesApp.SaleOrderInvoice')),
            ],
        ),
    ]
