# Generated by Django 2.2.1 on 2020-07-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorderinvoicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderinvoice',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='baseApp.Company'),
        ),
    ]
