# Generated by Django 2.2.1 on 2020-09-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorderinvoicesApp', '0002_auto_20200727_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderinvoice',
            name='invoice_number',
            field=models.CharField(max_length=56, unique=True),
        ),
        migrations.CreateModel(
            name='PublishedSaleOrderInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=56, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saleorderinvoicesApp.SaleOrderInvoice')),
            ],
        ),
    ]
