# Generated by Django 2.2.1 on 2020-09-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorderinvoicesApp', '0006_auto_20200907_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedsaleorderinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='saleorderinvoicesApp.SaleOrderInvoice'),
        ),
    ]
