# Generated by Django 2.2.1 on 2020-09-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorderinvoicesApp', '0007_auto_20200907_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedsaleorderinvoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='saleorderinvoicesApp.SaleOrderInvoice'),
        ),
    ]
