# Generated by Django 2.2.1 on 2020-09-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorderinvoicesApp', '0008_auto_20200908_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedsaleorderinvoice',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='published_invoice', to='saleorderinvoicesApp.SaleOrderInvoice'),
        ),
    ]
