# Generated by Django 2.2.1 on 2020-09-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saleorderinvoicesApp', '0010_auto_20200908_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderinvoiceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleordersApp.SaleOrderItem'),
        ),
    ]
