# Generated by Django 2.2.1 on 2020-09-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleorderinvoicesApp', '0012_auto_20200908_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderinvoice',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
