# Generated by Django 2.2.1 on 2020-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=16, unique=True)),
                ('item_description', models.CharField(max_length=192)),
                ('item_uom', models.CharField(max_length=16)),
                ('item_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('item_type', models.CharField(choices=[('GD', 'Goods'), ('SE', 'Services')], max_length=8)),
                ('item_sub_type', models.CharField(blank=True, choices=[('TS', 'Trade stock'), ('CS', 'Consumable Stock'), ('FA', 'Fixed Asset')], max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
