# Generated by Django 2.2.1 on 2020-07-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(max_length=16, unique=True)),
                ('supplier_name', models.CharField(max_length=128, unique=True)),
                ('supplier_address', models.CharField(max_length=264)),
                ('supplier_city', models.CharField(max_length=128)),
                ('supplier_phone', models.CharField(blank=True, max_length=128)),
                ('supplier_fax', models.CharField(blank=True, max_length=128)),
                ('supplier_email', models.EmailField(blank=True, max_length=192)),
                ('supplier_ntn_number', models.CharField(blank=True, max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
