# Generated by Django 2.2.1 on 2020-07-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0002_province'),
        ('customersApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(max_length=16, unique=True)),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('project_status', models.CharField(choices=[('Completed', 'Completed'), ('On-Going', 'On-Going'), ('Delivered', 'Delivered')], max_length=16)),
                ('contract_number', models.CharField(max_length=128, unique=True)),
                ('contract_signing_date', models.DateField()),
                ('award_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseApp.Company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customersApp.Customer')),
            ],
        ),
    ]
