# Generated by Django 2.2.1 on 2020-07-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0002_project_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='temp_field',
        ),
    ]
