# Generated by Django 2.2.1 on 2020-04-24 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crudbasic', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_number', models.CharField(max_length=24, verbose_name='Invoice Number')),
                ('si_tax_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tax Amount')),
                ('si_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Grand Total')),
                ('si_date', models.DateField(verbose_name='Invoice Date')),
                ('si_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Customers', verbose_name='Customer')),
                ('si_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Projects', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.CharField(max_length=24, verbose_name='SO Number')),
                ('so_ponumber', models.CharField(max_length=48, verbose_name='PO Number')),
                ('so_podate', models.DateField(null=True, verbose_name='PO Date')),
                ('so_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('so_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('so_draft', models.BooleanField(default=True)),
                ('so_publish', models.BooleanField(default=False)),
                ('so_publish_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('so_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Customers', verbose_name='Customer')),
                ('so_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Projects', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_line_number', models.IntegerField(verbose_name='Line')),
                ('so_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Quantity')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Sale Price')),
                ('so_item_tax_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tax Amount')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('variation_number', models.IntegerField(default=0)),
                ('variation_quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Variation Quantity')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('sale_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Items', verbose_name='Item')),
                ('so_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.SaleOrder')),
                ('so_tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.TaxRate')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_item_bill_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Quantity')),
                ('si_item_tax_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tax Amount')),
                ('si_item_total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Amount')),
                ('si_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.SaleOrderItem')),
                ('si_item_tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.TaxRate')),
                ('si_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.SaleInvoice')),
            ],
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='si_sonumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='salesApp.SaleOrder', verbose_name='SO Number'),
        ),
    ]
