# Generated by Django 2.2.1 on 2020-04-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorderitem',
            name='variation_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Variation Quantity'),
        ),
    ]
