# Generated by Django 2.2.1 on 2020-04-29 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0001_initial'),
        ('salesApp', '0002_auto_20200428_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_item_bill_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Quantity')),
                ('si_item_tax_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Tax Amount')),
                ('si_item_total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('si_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.SaleOrderItem')),
                ('si_item_tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crudbasic.TaxRate')),
            ],
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='si_number',
            field=models.CharField(max_length=24, null=True, verbose_name='Invoice Number'),
        ),
        migrations.DeleteModel(
            name='SaleInvoiceItems',
        ),
        migrations.AddField(
            model_name='saleinvoiceitem',
            name='si_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesApp.SaleInvoice'),
        ),
    ]
