# Generated by Django 2.2.1 on 2020-04-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0003_auto_20200429_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='si_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Customers', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='si_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crudbasic.Projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='saleinvoice',
            name='si_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Tax Amount'),
        ),
    ]
