# Generated by Django 2.2.1 on 2020-04-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0004_auto_20200430_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='si_sonumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salesApp.SaleOrder', verbose_name='SO Number'),
        ),
    ]
