# Generated by Django 2.2.1 on 2020-05-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0006_auto_20200430_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='billed_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Billed Quantity'),
        ),
        migrations.AddField(
            model_name='saleorderitem',
            name='unbilled_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Unbilled Quantity'),
        ),
    ]
