# Generated by Django 2.2.1 on 2020-05-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0007_auto_20200501_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorderitem',
            name='billed_quantity',
        ),
        migrations.RemoveField(
            model_name='saleorderitem',
            name='unbilled_quantity',
        ),
    ]
