# Generated by Django 2.2.1 on 2020-05-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0009_auto_20200515_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_podate',
            new_name='customer_po_date',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_ponumber',
            new_name='customer_po_number',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_draft',
            new_name='is_draft',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_publish',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_publish_date',
            new_name='publish_date',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_amount',
            new_name='tax_amount',
        ),
        migrations.RenameField(
            model_name='saleorder',
            old_name='so_tax_amount',
            new_name='total_amount',
        ),
    ]
