# Generated by Django 2.2.1 on 2020-05-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0011_auto_20200518_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='si_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='si_project',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='si_sonumber',
            new_name='sale_order',
        ),
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='si_tax_amount',
            new_name='tax_amount',
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
