# Generated by Django 2.2.1 on 2020-05-18 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0012_auto_20200518_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorderitem',
            old_name='sale_order_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='saleorderitem',
            old_name='so_quantity',
            new_name='order_quantity',
        ),
        migrations.RenameField(
            model_name='saleorderitem',
            old_name='so_number',
            new_name='sale_order',
        ),
        migrations.RenameField(
            model_name='saleorderitem',
            old_name='so_item_tax_amount',
            new_name='tax_amount',
        ),
        migrations.RenameField(
            model_name='saleorderitem',
            old_name='so_tax_rate',
            new_name='tax_rate',
        ),
    ]
