# Generated by Django 2.2.1 on 2020-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0013_auto_20200518_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='saleorderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Price'),
        ),
    ]
