# Generated by Django 2.2.1 on 2020-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0014_auto_20200518_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='billed_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Billed Quantity'),
        ),
        migrations.AlterField(
            model_name='saleorderitem',
            name='order_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Order Quantity'),
        ),
    ]
