# Generated by Django 2.2.1 on 2020-05-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0015_auto_20200518_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorderitem',
            old_name='sale_price',
            new_name='unit_price',
        ),
    ]
