# Generated by Django 2.2.1 on 2020-05-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0018_saleinvoiceitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Available Quantity'),
        ),
    ]
