# Generated by Django 2.2.1 on 2020-06-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0019_saleorderitem_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderitem',
            name='so_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='SO Amount'),
        ),
    ]
