# Generated by Django 2.2.1 on 2020-07-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0021_auto_20200623_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customersApp.Customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customersApp.Customer', verbose_name='Customer'),
        ),
    ]
