# Generated by Django 2.2.1 on 2020-07-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0023_auto_20200703_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoiceitem',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxesApp.Tax'),
        ),
        migrations.AlterField(
            model_name='saleorderitem',
            name='tax_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxesApp.Tax'),
        ),
    ]
