# Generated by Django 2.2.1 on 2020-07-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesApp', '0024_auto_20200707_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projectsApp.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsApp.Project', verbose_name='Project'),
        ),
    ]
