# Generated by Django 2.2.1 on 2020-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsApp', '0001_initial'),
        ('customersApp', '0001_initial'),
        ('projectsApp', '0003_remove_project_temp_field'),
        ('taxesApp', '0002_auto_20200706_1705'),
        ('salesApp', '0025_auto_20200708_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaleOrder',
            new_name='SaleOrder_obs',
        ),
        migrations.RenameModel(
            old_name='SaleOrderItem',
            new_name='SaleOrderItem_obs',
        ),
        migrations.RenameField(
            model_name='saleinvoice',
            old_name='sale_order',
            new_name='sale_order_obs',
        ),
        migrations.RenameField(
            model_name='saleinvoiceitem',
            old_name='sale_order_item',
            new_name='sale_order_item_obs',
        ),
        migrations.RenameField(
            model_name='saleorderitem_obs',
            old_name='sale_order',
            new_name='sale_order_obs',
        ),
    ]
