# Generated by Django 2.2.1 on 2020-07-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemsApp', '0001_initial'),
        ('customersApp', '0001_initial'),
        ('projectsApp', '0003_remove_project_temp_field'),
        ('taxesApp', '0002_auto_20200706_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=56, unique=True)),
                ('invoice_date', models.DateField()),
                ('amount_exclusive_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customersApp.Customer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projectsApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StandardInvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standardinvoiceApp.StandardInvoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='itemsApp.Item')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='taxesApp.Tax')),
            ],
        ),
    ]
