# Generated by Django 2.2.1 on 2020-07-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0004_department'),
        ('standardinvoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardinvoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='baseApp.Company'),
            preserve_default=False,
        ),
    ]
