# Generated by Django 2.2.1 on 2020-07-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardinvoiceApp', '0002_standardinvoice_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardinvoiceitem',
            name='line_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standardinvoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
