# Generated by Django 2.2.1 on 2019-09-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=16, unique=True)),
                ('customer_name', models.CharField(max_length=128, unique=True)),
                ('customer_address', models.CharField(max_length=264)),
                ('customer_city', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_line', models.CharField(max_length=16, unique=True)),
                ('item_description', models.CharField(max_length=192)),
                ('item_uom', models.CharField(max_length=16)),
                ('item_type', models.CharField(choices=[('Goods', 'Goods'), ('Services', 'Services')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=16, unique=True)),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('project_city', models.CharField(max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudbasic.Customers')),
            ],
        ),
    ]
