# Generated by Django 2.2.1 on 2019-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=192),
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_fax',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_ntn_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='customers',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_worth',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
