# Generated by Django 2.2.1 on 2020-06-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_tax',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
