# Generated by Django 2.2.1 on 2020-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0003_taxrate_tax_jurisdiction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='tax_jurisdiction',
            field=models.CharField(choices=[('KPK', 'Khyber Pakhtoonkhwa'), ('Punjab', 'Punjab'), ('Baluchistan', 'Baluchistan'), ('Sindh', 'Sindh'), ('Federal', 'Federal')], max_length=64),
        ),
    ]
