# Generated by Django 2.2.1 on 2020-06-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0004_auto_20200619_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='tax_jurisdiction',
            field=models.CharField(choices=[('KP', 'Khyber Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Baluchistan', 'Baluchistan'), ('Sindh', 'Sindh'), ('Federal', 'Federal')], max_length=64),
        ),
    ]
