# Generated by Django 2.2.1 on 2020-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0005_auto_20200619_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
