# Generated by Django 2.2.1 on 2020-07-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseApp', '0004_auto_20200703_1243'),
        ('salesApp', '0023_auto_20200703_1243'),
        ('crudbasic', '0007_auto_20200702_1735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
