# Generated by Django 2.2.1 on 2020-07-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0008_delete_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxRate',
        ),
    ]
