# Generated by Django 2.2.1 on 2020-07-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudbasic', '0009_delete_taxrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
